language: node_js
node_js:
- '6'
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_script:
- npm install --quiet -g gulp
- npm install
- echo "SKIP_PREFLIGHT_CHECK=true" > .env
before_deploy:
- travis_wait npm run build
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ryXRJA8cp5SXHw3Fw5iZmP204RXeDekz9aNc1w4zWL3E5mlPe7FiKOuCWUZI8DEg0PxwclIp8x8cvetH7SK+LMpVB0fbEmYHDBg4JjO0KSRYetdrN2/rWhf02Goi1io11t8/X3IIZdT57fY2rzX5OO2ZjBfArojiE8wro9NlG5HEcCXaS4y6qRmT9x47KlgbePKOJizPeJ29cCE1NUZE1TPW718dK/MpIPWXr/rU0N7bazxUbUoPmyLb2xjfpLn1K/7KwcfUcoB4y7LjiKLonFo0Xe0Y4zOlRDXUo+XQPpMAMSLPuti60L520LdrLIrjy6tVuZA1nyIznKdhUOdWwoHThxu1QK8MC1xuDpPJniRSTkWLEZPjgXkr4uP+WPo8E4csE46kEV926RY6RBsBxFERarEgeFqMbLrFVtomqFOWLLzL6C7SEcDr4fa9m6e5ZBWQ1cz2mopl1RRrxJAB711Rz8uY7IGs8UGJVJ6aIAYFlMmybpuJYBbf4mKVFJzhHux8hb6jS7DNRiH8CViGxRXDtYbgEtOe09gmVsTkxtCZHz5MigyYh+a1YzlanjCn5p77Xh30ji9sH2x/TSGfRdKju1vKqeI8tfQ8tytkWArGgufX4vTZKcWMG0G2XGTLPzArq8vjaZEMCSCQtJ64pDBfwxVB/Z5u8tg2d0EtI2Y=
  file: dist.zip
  on:
      tags: true
      branch: master
